name: tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    name: test-${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - run: python --version
      - run: pip --version

      # The following pinned dependencies must be updated manually
      - run: pip install nox==2024.4.15
      - run: pip install poetry==1.8.3

      - run: nox -s test-${{ matrix.python-version }}
